[package]
name = "mybops"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-schema = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
axum = { workspace = true, optional = true }
azure_core = { version = "0.4.0", optional = true }
azure_data_cosmos = { version = "0.5.0", optional = true }
reqwest = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }
serde.workspace = true
serde_arrow = { workspace = true, optional = true }
serde_json.workspace = true
serde_rusqlite = { workspace = true, optional = true }
sqlparser = { workspace = true, optional = true }

[features]
azure = ["dep:azure_core", "dep:azure_data_cosmos"]
full = ["dep:arrow-schema", "dep:async-trait", "dep:axum", "dep:reqwest", "dep:rusqlite", "dep:serde_arrow", "dep:serde_rusqlite", "dep:sqlparser"]
