[package]
name = "zeroflops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure_data_cosmos = { version = "0.5.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
azure = ["azure_data_cosmos"]
